/**
 * Daily Training Report Fixture Module
 * All dummy data lives HERE and nowhere else.
 */

import { todayISO, addDaysISO } from '../../../shared/utils/date';
import type { DailyReportData } from './daily-report.types';

export function makeDailyReportFixture(): DailyReportData {
  const today = todayISO();
  const d1 = addDaysISO(-9);
  const d2 = addDaysISO(-8);
  const d3 = addDaysISO(-7);
  const d4 = addDaysISO(-6);
  const d5 = addDaysISO(-5);
  const d6 = addDaysISO(-4);
  const d7 = addDaysISO(-3);
  const d8 = addDaysISO(-2);
  const d9 = addDaysISO(-1);

  const reportData: DailyReportData = {
    reportDate: today,
    batchId: 'batch-mim-2026-b1',
    batchCode: 'MIM-B1-2026',
    batchName: 'Batch 1 — Advanced Data Analytics & Power BI',
    collegeName: 'MIM Kuttikkanam',
    courseName: 'Data Analytics & Business Intelligence with Power BI',
    academicYear: '2025-2026',
    trainerName: 'Ajay V. Strategy',
    coordinatorName: 'Prof. Thomas Kurian',
    totalStudents: 20,
    courseMaxMarks: 100,
    finalExamPassMarkPercent: 70, // Course catalog pass % criteria
    finalExamTitle: 'Final Certification Exam — Power BI & Data Analytics',
    finalExamDate: today,
    assessments: [
      { id: 'ass-1', title: 'Excel Analytics & Formulas Test', type: 'Quiz', maxMarks: 100, passMarkPercent: 84, isCustomPassMark: false },
      { id: 'ass-2', title: 'SQL & Data Modeling Assessment', type: 'Practical', maxMarks: 100, passMarkPercent: 84, isCustomPassMark: false },
      { id: 'ass-3', title: 'Power BI Dashboard Challenge', type: 'Project', maxMarks: 100, passMarkPercent: 75, isCustomPassMark: true },
      { id: 'ass-4', title: 'Final Certification Practice Exam', type: 'Mock Exam', maxMarks: 100, passMarkPercent: 70, isCustomPassMark: true },
    ],
    sessions: [
      { date: d1, presentCount: 19, absentCount: 1, lateCount: 0, totalStudents: 20, attendancePct: 95, absentStudentIds: ['st-12'] },
      { date: d2, presentCount: 18, absentCount: 2, lateCount: 1, totalStudents: 20, attendancePct: 90, absentStudentIds: ['st-05', 'st-18'] },
      { date: d3, presentCount: 17, absentCount: 3, lateCount: 2, totalStudents: 20, attendancePct: 85, absentStudentIds: ['st-03', 'st-09', 'st-15'] },
      { date: d4, presentCount: 14, absentCount: 6, lateCount: 1, totalStudents: 20, attendancePct: 70, absentStudentIds: ['st-02', 'st-06', 'st-08', 'st-11', 'st-14', 'st-19'] },
      { date: d5, presentCount: 20, absentCount: 0, lateCount: 0, totalStudents: 20, attendancePct: 100, absentStudentIds: [] },
      { date: d6, presentCount: 18, absentCount: 2, lateCount: 1, totalStudents: 20, attendancePct: 90, absentStudentIds: ['st-04', 'st-16'] },
      { date: d7, presentCount: 19, absentCount: 1, lateCount: 0, totalStudents: 20, attendancePct: 95, absentStudentIds: ['st-10'] },
      { date: d8, presentCount: 13, absentCount: 7, lateCount: 3, totalStudents: 20, attendancePct: 65, absentStudentIds: ['st-02', 'st-05', 'st-07', 'st-11', 'st-13', 'st-17', 'st-20'] },
      { date: d9, presentCount: 19, absentCount: 1, lateCount: 1, totalStudents: 20, attendancePct: 95, absentStudentIds: ['st-09'] },
      { date: today, presentCount: 18, absentCount: 2, lateCount: 0, totalStudents: 20, attendancePct: 90, absentStudentIds: ['st-02', 'st-11'] },
    ],
    students: [
      {
        id: 'st-01',
        registerNo: '9847011221',
        phone: '9847011221',
        name: 'Abhirami S. Kumar',
        email: 'abhirami.s@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Female',
        qualification: 'B.Tech CS',
        hasComputer: 'Yes',
        learnedBefore: 'Yes',
        attendancePct: 98,
        totalPresent: 10,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 92, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-2': { marks: 88, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 95, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-4': { marks: 85, maxMarks: 100, grade: 'A', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 92,
        finalExamResult: 'Passed',
        remarks: 'Excellent performance in DAX and SQL.',
      },
      {
        id: 'st-02',
        registerNo: '9447122334',
        phone: '9447122334',
        name: 'Alan Joseph',
        email: 'alan.j@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'B.Com',
        hasComputer: 'No',
        learnedBefore: 'No',
        attendancePct: 68,
        totalPresent: 7,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 65, maxMarks: 100, grade: 'C', passed: false, attempted: true },
          'ass-2': { marks: 72, maxMarks: 100, grade: 'B', passed: false, attempted: true },
          'ass-3': { marks: 80, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
          'ass-4': { marks: 0, maxMarks: 100, grade: 'F', passed: false, attempted: false },
        },
        assessmentStatus: 'Failed',
        finalExamEligibility: 'Not Eligible',
        finalExamMark: 54,
        finalExamResult: 'Failed',
        eligibilityReason: 'Failed prerequisite assessments (Excel, SQL) & Mock Exam.',
        remarks: 'Requires retest for Excel and SQL.',
      },
      {
        id: 'st-03',
        registerNo: '9745233445',
        phone: '9745233445',
        name: 'Anu Mary Philip',
        email: 'anumary@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Female',
        qualification: 'BCA',
        hasComputer: 'Yes',
        learnedBefore: 'No',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 86, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-2': { marks: 84, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 78, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
          'ass-4': { marks: 76, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 82,
        finalExamResult: 'Passed',
        remarks: 'Good progress in Power BI visualization.',
      },
      {
        id: 'st-04',
        registerNo: '9846344556',
        phone: '9846344556',
        name: 'Arjun R. Nair',
        email: 'arjun.r@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'B.Tech CS',
        hasComputer: 'Yes',
        learnedBefore: 'Yes',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 85, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-2': { marks: 86, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 82, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-4': { marks: 78, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 85,
        finalExamResult: 'Passed',
        remarks: 'Consistently clear concepts.',
      },
      {
        id: 'st-05',
        registerNo: '9142455667',
        phone: '9142455667',
        name: 'Bibin Mathew',
        email: 'bibin.m@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'B.Com',
        hasComputer: 'No',
        learnedBefore: 'No',
        attendancePct: 80,
        totalPresent: 8,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 70, maxMarks: 100, grade: 'C', passed: false, attempted: true },
          'ass-2': { marks: 85, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 88, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-4': { marks: 74, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
        },
        assessmentStatus: 'Failed',
        finalExamEligibility: 'Not Eligible',
        finalExamMark: 62,
        finalExamResult: 'Failed',
        eligibilityReason: 'Failed Excel Analytics assessment (70% vs 84% pass mark).',
        remarks: 'Retest scheduled for Excel.',
      },
      {
        id: 'st-06',
        registerNo: '9633566778',
        phone: '9633566778',
        name: 'Devika P. Menon',
        email: 'devika.p@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Female',
        qualification: 'MCA',
        hasComputer: 'Yes',
        learnedBefore: 'Yes',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 94, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-2': { marks: 91, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-3': { marks: 96, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-4': { marks: 92, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 98,
        finalExamResult: 'Passed',
        remarks: 'Top scorer of the batch.',
      },
      {
        id: 'st-07',
        registerNo: '9562677889',
        phone: '9562677889',
        name: 'Gautham S. Varma',
        email: 'gautham.v@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'BCA',
        hasComputer: 'Yes',
        learnedBefore: 'No',
        attendancePct: 85,
        totalPresent: 8,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 88, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-2': { marks: 89, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 0, maxMarks: 100, grade: 'F', passed: false, attempted: false },
          'ass-4': { marks: 80, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
        },
        assessmentStatus: 'Pending',
        finalExamEligibility: 'Not Eligible',
        finalExamMark: 76,
        finalExamResult: 'Passed',
        eligibilityReason: 'Not attempted Power BI Dashboard Challenge.',
        remarks: 'Absence during project submission.',
      },
      {
        id: 'st-08',
        registerNo: '9895788990',
        phone: '9895788990',
        name: 'Haripriya K.',
        email: 'haripriya.k@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Female',
        qualification: 'B.Tech CS',
        hasComputer: 'Yes',
        learnedBefore: 'Yes',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 90, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-2': { marks: 87, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 85, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-4': { marks: 82, maxMarks: 100, grade: 'A', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 89,
        finalExamResult: 'Passed',
        remarks: 'Strong analytical skills.',
      },
      {
        id: 'st-09',
        registerNo: '9496899001',
        phone: '9496899001',
        name: 'Jithin Thomas',
        email: 'jithin.t@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'B.Sc IT',
        hasComputer: 'Yes',
        learnedBefore: 'No',
        attendancePct: 80,
        totalPresent: 8,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 84, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-2': { marks: 84, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 76, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
          'ass-4': { marks: 71, maxMarks: 100, grade: 'B', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 78,
        finalExamResult: 'Passed',
        remarks: 'Cleared all assessments.',
      },
      {
        id: 'st-10',
        registerNo: '9747900112',
        phone: '9747900112',
        name: 'Kavya Suresh',
        email: 'kavya.s@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Female',
        qualification: 'MCA',
        hasComputer: 'Yes',
        learnedBefore: 'Yes',
        attendancePct: 95,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 91, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-2': { marks: 93, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-3': { marks: 90, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-4': { marks: 88, maxMarks: 100, grade: 'A', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 91,
        finalExamResult: 'Passed',
        remarks: 'Active participant.',
      },
      {
        id: 'st-11',
        registerNo: '9446011223',
        phone: '9446011223',
        name: 'Manish Kumar G.',
        email: 'manish.g@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'B.Com',
        hasComputer: 'No',
        learnedBefore: 'No',
        attendancePct: 70,
        totalPresent: 7,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 60, maxMarks: 100, grade: 'F', passed: false, attempted: true },
          'ass-2': { marks: 65, maxMarks: 100, grade: 'F', passed: false, attempted: true },
          'ass-3': { marks: 70, maxMarks: 100, grade: 'C', passed: false, attempted: true },
          'ass-4': { marks: 55, maxMarks: 100, grade: 'F', passed: false, attempted: true },
        },
        assessmentStatus: 'Failed',
        finalExamEligibility: 'Not Eligible',
        finalExamMark: 48,
        finalExamResult: 'Failed',
        eligibilityReason: 'Failed all prerequisite assessments and low attendance (70%).',
        remarks: 'High risk student. Intensive remedial training required.',
      },
      {
        id: 'st-12',
        registerNo: '9845122334',
        phone: '9845122334',
        name: 'Nevin K. Paul',
        email: 'nevin.p@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'BCA',
        hasComputer: 'Yes',
        learnedBefore: 'Yes',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 87, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-2': { marks: 85, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 89, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-4': { marks: 79, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 84,
        finalExamResult: 'Passed',
        remarks: 'Consistent.',
      },
      {
        id: 'st-13',
        registerNo: '9746233445',
        phone: '9746233445',
        name: 'Pooja R. Krishnan',
        email: 'pooja.k@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Female',
        qualification: 'B.Tech CS',
        hasComputer: 'Yes',
        learnedBefore: 'Yes',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 95, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-2': { marks: 92, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-3': { marks: 94, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-4': { marks: 90, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 94,
        finalExamResult: 'Passed',
        remarks: 'Exceptional quality dashboards.',
      },
      {
        id: 'st-14',
        registerNo: '9495344556',
        phone: '9495344556',
        name: 'Rahul V. Pillai',
        email: 'rahul.p@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'B.Sc IT',
        hasComputer: 'Yes',
        learnedBefore: 'No',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 86, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-2': { marks: 88, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 82, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-4': { marks: 75, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 81,
        finalExamResult: 'Passed',
        remarks: 'Cleared all modules.',
      },
      {
        id: 'st-15',
        registerNo: '9896455667',
        phone: '9896455667',
        name: 'Riya Elizabeth',
        email: 'riya.e@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Female',
        qualification: 'MCA',
        hasComputer: 'Yes',
        learnedBefore: 'Yes',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 89, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-2': { marks: 87, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 91, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-4': { marks: 83, maxMarks: 100, grade: 'A', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 88,
        finalExamResult: 'Passed',
        remarks: 'Strong data model grasp.',
      },
      {
        id: 'st-16',
        registerNo: '9744566778',
        phone: '9744566778',
        name: 'Siddharth M.',
        email: 'siddharth.m@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'BCA',
        hasComputer: 'Yes',
        learnedBefore: 'No',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 85, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-2': { marks: 86, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 80, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
          'ass-4': { marks: 74, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 79,
        finalExamResult: 'Passed',
        remarks: 'Good progress.',
      },
      {
        id: 'st-17',
        registerNo: '9447677889',
        phone: '9447677889',
        name: 'Sneha B. Nambiar',
        email: 'sneha.n@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Female',
        qualification: 'B.Tech CS',
        hasComputer: 'Yes',
        learnedBefore: 'Yes',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 92, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-2': { marks: 90, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-3': { marks: 88, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-4': { marks: 86, maxMarks: 100, grade: 'A', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 90,
        finalExamResult: 'Passed',
        remarks: 'Very diligent.',
      },
      {
        id: 'st-18',
        registerNo: '9846788990',
        phone: '9846788990',
        name: 'Suraj S. Kurup',
        email: 'suraj.k@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'B.Sc IT',
        hasComputer: 'Yes',
        learnedBefore: 'No',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 84, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-2': { marks: 85, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 82, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-4': { marks: 72, maxMarks: 100, grade: 'B', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 77,
        finalExamResult: 'Passed',
        remarks: 'Eligible for final exam.',
      },
      {
        id: 'st-19',
        registerNo: '9745899001',
        phone: '9745899001',
        name: 'Varun K. Sharma',
        email: 'varun.s@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'BCA',
        hasComputer: 'Yes',
        learnedBefore: 'Yes',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 88, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-2': { marks: 86, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 84, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-4': { marks: 78, maxMarks: 100, grade: 'B+', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 83,
        finalExamResult: 'Passed',
        remarks: 'Active learner.',
      },
      {
        id: 'st-20',
        registerNo: '9496900112',
        phone: '9496900112',
        name: 'Vidyut C. Prakash',
        email: 'vidyut.p@mim.edu.in',
        college: 'MIM Kuttikkanam',
        batch: 'Batch 1',
        gender: 'Male',
        qualification: 'B.Tech CS',
        hasComputer: 'Yes',
        learnedBefore: 'Yes',
        attendancePct: 90,
        totalPresent: 9,
        totalSessions: 10,
        assessmentScores: {
          'ass-1': { marks: 91, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-2': { marks: 89, maxMarks: 100, grade: 'A', passed: true, attempted: true },
          'ass-3': { marks: 93, maxMarks: 100, grade: 'A+', passed: true, attempted: true },
          'ass-4': { marks: 87, maxMarks: 100, grade: 'A', passed: true, attempted: true },
        },
        assessmentStatus: 'Completed',
        finalExamEligibility: 'Eligible',
        finalExamMark: 93,
        finalExamResult: 'Passed',
        remarks: 'Excellent practical skills.',
      },
    ],
    progressMilestones: [
      { date: d1, sessionNo: 1, topicCovered: 'Advanced Excel Formulas, XLOOKUP & Pivot Tables', practicalDone: true, status: 'Completed' },
      { date: d2, sessionNo: 2, topicCovered: 'Power Query Data Transformation & Cleaning', practicalDone: true, status: 'Completed' },
      { date: d3, sessionNo: 3, topicCovered: 'Relational Data Modeling & Star Schema Design', practicalDone: true, status: 'Completed' },
      { date: d4, sessionNo: 4, topicCovered: 'SQL Joins, Aggregations & Window Functions', practicalDone: true, status: 'Completed' },
      { date: d5, sessionNo: 5, topicCovered: 'DAX Basics: Calculated Columns & Measures', practicalDone: true, status: 'Completed' },
      { date: d6, sessionNo: 6, topicCovered: 'Time Intelligence Functions in DAX', practicalDone: true, status: 'Completed' },
      { date: d7, sessionNo: 7, topicCovered: 'Interactive Visualizations & Custom Tooltips', practicalDone: true, status: 'Completed' },
      { date: d8, sessionNo: 8, topicCovered: 'Power BI Desktop to Service Publishing & RLS', practicalDone: true, status: 'Completed' },
      { date: d9, sessionNo: 9, topicCovered: 'Real-World Capstone Dashboard Construction', practicalDone: true, status: 'Completed' },
      { date: today, sessionNo: 10, topicCovered: 'Final Certification Exam & Evaluation', practicalDone: true, status: 'Completed' },
    ],
    riskItems: [
      {
        studentId: 'st-02',
        studentName: 'Alan Joseph',
        registerNo: '9447122334',
        riskReason: 'Multiple Issues',
        attendancePct: 68,
        failedCount: 2,
        severity: 'High',
      },
      {
        studentId: 'st-11',
        studentName: 'Manish Kumar G.',
        registerNo: '9446011223',
        riskReason: 'Multiple Issues',
        attendancePct: 70,
        failedCount: 4,
        severity: 'High',
      },
      {
        studentId: 'st-05',
        studentName: 'Bibin Mathew',
        registerNo: '9142455667',
        riskReason: 'Failed Assessments',
        attendancePct: 80,
        failedCount: 1,
        severity: 'Medium',
      },
    ],
    certificateStatus: [
      {
        printed: true,
        deliveredToCollege: false,
        deliveryDate: addDaysISO(5),
        printedCount: 17,
        totalCount: 20,
        remarks: 'Certificates printed for eligible students (17/20). Pending college dispatch.',
      },
    ],
    attachments: [
      { id: 'att-1', fileName: 'MIM_Batch1_Attendance_Log.pdf', fileType: 'PDF Document', fileSize: '1.2 MB', uploadedBy: 'Ajay V. Strategy', uploadedAt: today },
      { id: 'att-2', fileName: 'Excel_PowerBI_Assessment_Grades.xlsx', fileType: 'Excel Spreadsheet', fileSize: '480 KB', uploadedBy: 'Ajay V. Strategy', uploadedAt: today },
      { id: 'att-3', fileName: 'Capstone_Dashboard_Screenshots.zip', fileType: 'ZIP Archive', fileSize: '4.8 MB', uploadedBy: 'Ajay V. Strategy', uploadedAt: today },
    ],
    defaultTrainerNotes: 'Final Certification Exam conducted for Batch 1 at MIM Kuttikkanam. 17 out of 20 students (85%) passed the final certification exam. Students with prior programming background and laptop access scored higher average marks.',
  };

  return reportData;
}
