import React from 'react';
import type { DailyReportData, DailyReportConfig } from './daily-report.types';
import { SECTIONS } from './daily-report.registry';

interface DailyReportDocumentProps {
  data: DailyReportData;
  config: DailyReportConfig;
}

export const DailyReportDocument: React.FC<DailyReportDocumentProps> = ({ data, config }) => {
  const activeSections = SECTIONS.filter((s) => config.selectedSections.includes(s.id));

  return (
    <div
      className="daily-report-document"
      style={{
        width: '100%',
        maxWidth: '850px',
        margin: '0 auto',
        background: '#ffffff',
        color: '#0f172a',
        fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
        padding: '24px 32px',
        boxSizing: 'border-box',
        boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
        borderRadius: 6,
      }}
    >
      {/* Global Document Print Style Overrides */}
      <style>{`
        @media print {
          @page {
            size: A4 portrait;
            margin: 12mm;
          }
          body {
            background: #ffffff !important;
            color: #0f172a !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          .daily-report-document {
            box-shadow: none !important;
            padding: 0 !important;
            max-width: 100% !important;
          }
          .daily-report-no-print {
            display: none !important;
          }
          table {
            page-break-inside: auto;
          }
          tr {
            page-break-inside: avoid;
            page-break-after: auto;
          }
          thead {
            display: table-header-group;
          }
        }
      `}</style>

      {/* SINGLE Executive Header (Logo rendered ONCE) */}
      <div style={{ borderBottom: '2px solid #0f172a', paddingBottom: 12, marginBottom: 20 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            {/* KVJ LOGO ONLY — SINGLE instance at top left */}
            <img src="/logo.png" alt="KVJ Logo" style={{ height: 44, width: 'auto', display: 'block' }} />
          </div>
          <div style={{ textAlign: 'right' }}>
            <h1 style={{ margin: 0, fontSize: 20, fontWeight: 900, color: '#0f172a', letterSpacing: '-0.02em' }}>
              Daily Training Report
            </h1>
            <div style={{ fontSize: 11.5, fontWeight: 700, color: '#2563eb', marginTop: 2 }}>
              {data.collegeName} — {data.courseName}
            </div>
          </div>
        </div>

        {/* Sub-header Metadata Bar */}
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginTop: 10,
            paddingTop: 8,
            borderTop: '1px solid #e2e8f0',
            fontSize: 10.5,
            color: '#334155',
            flexWrap: 'wrap',
            gap: 8,
            background: '#f8fafc',
            padding: '6px 10px',
            borderRadius: 6,
          }}
        >
          <span><strong>Report Date:</strong> {data.reportDate}</span>
          <span><strong>Batch:</strong> {data.batchCode} ({data.batchName})</span>
          <span><strong>Academic Year:</strong> {data.academicYear}</span>
          <span><strong>Trainer:</strong> {data.trainerName}</span>
          <span><strong>Coordinator:</strong> {data.coordinatorName}</span>
        </div>
      </div>

      {/* Render Active Streamlined Sections */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        {activeSections.map((sec) => {
          const SectionComponent = sec.component;
          return (
            <div key={sec.id}>
              <SectionComponent data={data} config={config} />
            </div>
          );
        })}
      </div>

      {/* Document Footer */}
      <div
        style={{
          marginTop: 24,
          paddingTop: 10,
          borderTop: '1.5px solid #cbd5e1',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          fontSize: 9.5,
          color: '#64748b',
        }}
      >
        <div>
          Generated on {data.reportDate} at {new Date().toLocaleTimeString()} · Generated By: {data.trainerName}
        </div>
        <div style={{ fontWeight: 700, color: '#0f172a' }}>
          Confidential — KVJ Analytics Training Document
        </div>
      </div>
    </div>
  );
};
